### ISSUE TITLE
Kindly Build A ChatBar Component To Add To Our Homepage. (The Component Will Not Include Chat Functionality) - Plus 30 steem

### ISSUE THREAD

**Issue by surpassinggoogle** [surpassinggoogle/UlogsV2#181]
**Complexity:** Very simple!

### Task

Simply build a component that look like this:

![new ulog designs](https://user-images.githubusercontent.com/23729959/51299470-90817b00-1a63-11e9-92dc-3be90d555059.png)

This chat-bar component will later be added to parts of our homepage and certain pages across ulogs.org

#### Brief explanation of the chat-bar component.

While we expect you to build a chat-bar component, we don't expect you to build actual chat/direct-message function within this task. Assume that you will be building a dummy chat-bar component, that pulls and displays our list of "certified uloggers" i.e [the followed list of the @uloggers account](http://steemit.com/@uloggers/followed) and allows users to search these users by username or by typing in alphabets etc
.
However, whenever users tries to click on a user account in an attempt to send a chat, they will be provided with an alert like, "This DM feature is coming soon".

Also note that the user status, that is, offline/online/busy etc should be 'dummy' indicators.

#### Notice
Kindly check the current code. A previous developer attempted to build the component (It may have been commented out). You can look for that that exists and enhance it or you can build yours afresh. Kindly follow existing styling for consistency.

If you intend to build the component afresh, you may find similar components on areas of our website e.g on the right side of our homepage, an area labelled "interest people" as seen below:
![new ulog designs 2](https://user-images.githubusercontent.com/23729959/51300481-02a78f00-1a67-11e9-93dd-cc07901ea992.png)

**Comment by gregjava** [comment]
Ok.

**Comment by gregjava** [comment]
Fiverr
    
    
            
      {
          "@context": "http://schema.org",
          "@type": "EmailMessage",
          "action": {
            "@type": "ViewAction",
            "url": "https://www.fiverr.com/s2/c94b1313ff",
            "name": "Browse Services on Fiverr"
          },
          "description": "Browse Services on Fiverr"
      }
    

        
            
                
                    
                        
                            
                                
                                    
                                        
                                    
                                
                                
                                    
                                    
                                
                                
                                    

                                        
    

    
        Aburime is tired of keeping Fiverr a secret.
    

    
        Discover the easiest way to hire online freelancers and get 20% off your first order. From marketing to tech, complete all your projects on Fiverr. On budget. On time.
    

    
        Sounds too good to be true? See for yourself!
    



                                        
                                            
                                                
                                                    
                                                        
                                                            Browse Services On Fiverr
                                                        
                                                    
                                                
                                                
                                                    
                                                        

		
			
			
			The Fiverr Team
		
                                                    
                                                
                                            
                                        
                                    
                                
                            
                        
                    
                
                
                    
                        
                            
                                

                                    © Fiverr International Limited 2010-2019, Fiverr Inc. | 401 Broadway, Suite 1600 New York NY, 10013 USA.
                                    Your personal information will not be stored or used for any marketing purposes.
                                
                            
                         
                    
                
            
        
            

    If you would like to unsubscribe and stop receiving these emails  click here .
