### ISSUE TITLE
Help Reshape The Structure Of Certain Ulog-Subtag URL-space, To Look Like 'Communities'. - Plus 100 steem

### ISSUE THREAD

**Issue by surpassinggoogle** [surpassinggoogle/UlogsV2#183]
### Complexity
> Pretty Easy

### Task
> You will need the components created in #181 and #182 for this task.

In this task, we would like you to modify the structure of certain ulog-subtag-URL-spaces **(prior/after-login)**, by adding more components to these pages, turning them into ulog-communities.

**Below, i will cite the list of existing ulog-communities across ulogs.org, so that you easily find each:**

- https://ulogs.org/created/ulog-diy
- https://ulogs.org/created/ulog-howto
- https://ulogs.org/created/ulog-ned
- https://ulogs.org/created/ulog-surpassinggoogle
- https://ulogs.org/created/ulog-quotes
- https://ulogs.org/created/ulog-snookmadedoit
- https://ulogs.org/created/ulogifs
- https://ulogs.org/created/ulog-memes
- https://ulogs.org/created/ulog-utopian
- https://ulogs.org/created/ulog-blocktrades
- https://ulogs.org/created/ulog-bobbylee
- https://ulogs.org/created/ulog-showerthoughts
- https://ulogs.org/created/ulog-gratefulvibes
- https://ulogs.org/created/ulog-kusknee
- https://ulogs.org/created/ulog-papapepper
- https://ulogs.org/created/ulography
- https://ulogs.org/created/ulog-teamsteem
- https://ulogs.org/created/ulog-dimimp
- https://ulogs.org/created/ulog-steemjet
- https://ulogs.org/created/ulog-sweetsssj
- https://ulogs.org/created/ulog-surfyogi
- https://ulogs.org/created/ulog-resolutions

**Then, two core communities that form part of the ulogs.org ecosystem:**

- https://ulogs.org/created/teardrops
- https://ulogs.org/created/untalented

The general UI-structure for each of the addresses enlisted above, will now look like the image shown below: 
![new ulog design](https://user-images.githubusercontent.com/23729959/51329629-de70a000-1ab0-11e9-840d-f2f0c541a1cf.png)

Looking at the image above, just under the 'Overseeing Uloggers' column, you will need to add an area for labelled 'Direct Messaging' & 'Ulog-Games/Exchanges', that users can expand at will. 

When they expand each of these areas, it will open the following components:
1. 
![new ulog designs](https://user-images.githubusercontent.com/23729959/51330211-04e30b00-1ab2-11e9-8c5c-99cecdea0198.png)
2. 
![image](https://user-images.githubusercontent.com/23729959/51301213-5ca95400-1a69-11e9-9d02-36c037b468cc.png)

> Read more about these two components on #181 & #182 

Now, the **'About Community' Column**, will be titled according to the name of the Ulog-Community. I can provide you the 'raw text' for each one, when you take up the task.

On the 'About Community' column, you will notice the 'Post Now' button! We currently have 5 ulog-communities that have "dedicated post-editors". This means that the 'Post Now' button for these 5 ulog-communities should lead directly to respective dedicated post-editors. 

**Below, i will enlist the 5 ulog-communities and the URL for their respective dedicated editors:**  

- The ulog-diy 'Post Now' button should lead to the editor on 'https://ulogs.org/ulog-diy'
- The ulog-howto 'Post Now' button should lead to the editor on 'https://ulogs.org/ulog-howto'
- The ulog-ned 'Post Now' button should lead to the editor on 'https://ulogs.org/ulog-ned'
- The ulog-quotes 'Post Now' button should lead to the editor on 'https://ulogs.org/ulog-diy'
- The ulog-surpassinggoogle 'Post Now' button should lead to the editor on 'https://ulogs.org/ulog-surpassinggoogle'

Bonus:

- The #Teardrops 'Post Now' button should lead to the editor on 'https://ulogs.org/teardrops'
- The #Untalented 'Post Now' button should lead to the editor on 'https://ulogs.org/untalented'

> As for the remaining 'ulog-communities' that don't yet have their own 'dedicated editor', their 'Post Now' button should all lead to 'https://ulogs.org/main-editor'

**The video embed area:** For now, we don't have all the videos ready for these segments. I will provide you with the available videos when you take up the task. In the meantime, you can use this video (https://youtu.be/kKZ1CixLG2s) as default for each one.

Finally, the **"Quick Editor"** for each ulog-community e.g [#ulog-diy](https://ulogs.org/created/ulog-diy), already has [#ulog](https://ulogs.org/created/ulog) as its first default tag. We would now like you to add a second default tag 
e.g the "Quick Editor" of https://ulogs.org/created/ulog-diy, should be '#ulog-diy and so on and so forth.

**Comment by nirvanaitsolutions** [comment]
PLease assign the task to us
