### ISSUE TITLE
Adjust The Structure Of Our Homepage & Pages Across Ulogs.org (Prior/Post-Login) - Plus 100 steem

### ISSUE THREAD

**Issue by surpassinggoogle** [surpassinggoogle/UlogsV2#184]
### Complexity
> Pretty Easy

### Task
> You will need the components created in #181 and #182 for this task. 

In this task, we would like you to modify the general structure of our homepage and pages in general across ulogs.org **(prior/after-login)**, by adding more components to these pages.

Our homepage structure currently looks like this (upon login):
![image](https://steemitimages.com/p/2N61tyyncFaFVtpM8rCsJzDgecVMtkz4jpzBsszXjhqan9oSZc3p4mhvfNsKi13hLB3zSZJm5RQtot2caUWFeQ4J7LyFY9QJP5MXczEUNk1yy3zejHJSZ9WH4pS8198i8cBA8FkSix4e?format=match&mode=fit&width=640)

We now want our homepage structure (upon login) to look like this:
![image](https://steemitimages.com/p/mCz6aUXpYgcPMkrb3nPoyTzkzdc5iGt2s1Cj9WtT6JEHk6HZJabhf6mhPM5sGB8WjDYc9tm8yAByUd2Nit8LXQnwTrYntf7wr6A4wbcSbcFFeTzPEeD6VgyGmwETmBFm4uzbyM25uy1gzLGrD8NBfZn5pWtyVT5nY8pgMoaJFY7d8ouJVjqZUR34Arq9bQRWcumzaYM2tA7WSjMEoEeFrsUw6KRztJq8MYjNp6JaawhtYgMqeri6ECoEABNY62oWUpZbbhDPdgngN5oHcq3sfAnnX6ivD1AP?format=match&mode=fit&width=640)

Prior to login, our current homepage looks like this:
![image](https://steemitimages.com/p/C3TZR1g81UNaPs7vzNXHueW5ZM76DSHWEY7onmfLxcK2iPPQiZzQJiowxCvF27pfAT6H93LNb1Y69ppDpCWHf9n1HcmmfTXM55Y1Upg9oNyFNPMZAtEyvdU?format=match&mode=fit&width=640)

At the end of this task, our homepage (prior to login) should now look like this:
![image](https://steemitimages.com/p/5ZJ4Z52ZRyQgKo6LcCMfsipjRiHmNbziM1uAihU5SRvDqDdfxFSogHK5LXAtRLpMbyCeThnyHwcH9WmFQ49avdw1uNoEkrdp8ybhrRTLZw1XpZGs8q6T4iGoRa7VbzTKEp5w9wkmctueQh4viWwrBZ4kGRMCgQuzLwmucbrsDiiR7UYyJVxVTD7fTTjq5WTC5PwTEkgqTj81hJKQk365vNeEP4HRYQUjvZxniikhGRcWGSTg3nJSB62bTPVGBauDE3MfMrLoS13m21VaojJnsSf?format=match&mode=fit&width=640)

> As seen in the screenshot above, some items will require login to proceed e.g the **'direct message'** area and the **'Add a ulog-story'** button.

Now that we have established the new general look for our homepage, we can apply the new look across every hashtag URL-space e.g #steemit #travel #busy etc, excluding ulog-related hashtags like #ulog-utopian #ulog-diy etc (Refer to #183 to see some of the ulog-related tags that are excempted because the carry their own look)

Hashtag like #steemit, #travel, #busy etc will now carry a look that tallies with our new default page structure:
![image](https://steemitimages.com/p/Ly4dsQuP1jo5KGQd1kc11DUQsphuEgBcMYKZrFA6CLAU3YQ117yiHmmkXRxqMTnGvv7NzBduMJFF9WkihNZf2G8GTTVq3GexLtAaqHvBuzay2ubWqChZ75J2teyHc1Lt4QFwVdZabyrrHLGcrb7fTHoAs7txX2PMT3BgBmeSEJWajDEgsy649s4gp86MMPPkn1aZTohohETtL3MDW4SBMwYPH7PN8bLbhm3VpkR822jvvFuNm7siLQrjFxtgGguVRg8zK2AwAys3ZrXFGXeyszEo3xVjmMZtcoFm9Zskr19pgBMQYV7aX9kTKuso5Bc3pVYKEwJ2Kb7qhyqZPVJa4GUgoyMARxv63dKA79YJLuk5CbfFiXocxA5M5pmsXgYjhMV59VvuUPT6FiYvUcRnaKALd3dVFpMSjgcKHNSBNBXBbZzCP7FkKozNpLRWZGaXAgrqt7NKKioRpyd?format=match&mode=fit&width=640)

Reference: #181, #182 & #183

**Comment by nirvanaitsolutions** [comment]
Please assign the the task to us
