### ISSUE TITLE
Let's Complete Our 'Ulog-Stories Column' On The Homepage Of Ulogs.org - Plus 70 steem

### ISSUE THREAD

**Issue by surpassinggoogle** [surpassinggoogle/UlogsV2#185]
**Complexity:** Pretty Easy.

We currently have a column on our homepage called the 'Ulog-stories' column. This component is only partially functional. We would like to make it fully functional.
![image](https://user-images.githubusercontent.com/23729959/51440446-16225680-1d02-11e9-8a94-5203f5d4498c.png)

### Current Behavior
The Ulog-Stories currently displays a random selection of user-profiles from our list of certified uloggers. (The ulog-stories column is designed to display only "certified uloggers" at every instance.)
Each user-profile also carries a 'view' button, which isn't yet functional. 
When users click on the 'Add a ulog-story' button currently, it doesn't work. (Please look in the code as this may be as a result of a bug or perhaps, it has been commented out. Normally, users are led to a functional 'quick editor' that looks this):
![image](https://steemitimages.com/p/C3TZR1g81UNaPs7vzNXHueW5ZM76DSHWEY7onmfLxcK2iNzZAo3cJtkDLZXTAqjfuA1wMhpT4W583Xp9R23AAYzxCRWLhrpSmh8B15LekxtmxfmCAh2QWkn?format=match&mode=fit&width=640)

### Expected Behavior
At the end of this task, we want an entirely functional 'Ulog-Stories' column. To this effect, i will related all our expectation afresh.....

The "add the ulog-story" button, when clicked upon, should open a simple portal like this below:
![image](https://steemitimages.com/p/9vWp6aU4y8kwSZ9Gw15LFL3aMdhmgmBBFMpDJregpdP328XNhudTr3gHj2iptMS9zvsat9iSyXdFAiUSUNTfvqVRgJQhbC117DRVvCQWu7aK4QKcpijHyeXALpPTNEtt8EdiJFtNKRjaFckDk?format=match&mode=fit)

Incase you are building the features afresh, note that we already have a 'quick editor' across ulogs.org that you can replicate and currently, this 'quick editor' already has '#ulog' as the default first tag.

See this:
![image](https://steemitimages.com/p/gPCasciUWmEwHnsXKML7xF4NE4zxEVyvENsPKp9LmDaFv1zvBirsuEJg6DVLAoJn5dkNPXRzzAixRgwSDo6uGiYxSQYE8DNDNF1LYWY1ozi1pcGk2S75gRzJGqBe3S53Sehe149ks4QCsixCPx?format=match&mode=fit)

The difference however is, for the 'Ulog-stories quick editor', you will now need to add a 'categories tab' function, that allows users to select from a list of Ulog-Stories 'categories'. You will also need to add a 'select payout-type' function.

When users select a category, the 'Selected categories' will now form the second hashtag for the eventually created post, with '#ulog' already constituting the first default hashtag.

Below is the list of current Ulog-Stories categories that will make up the 'select a category' component.

- #ulog-images 
- #ulography 
- #ulog-graphics 
- #ulogifs 
- #ulog-news 
- #ulog-arts 
- #ulog-unfinishedarts 
- #ulog-drafts
- #ulog-memes 
- #ulog-resolutions 
- #ulog-quotes 
- #ulog-showerthoughts
- #ulog-snookmademedoit

For instance, if a user uses the Ulog-Stories editor and selects '#ulog-unfinishedarts' as category, this becomes the second tag for his post (where '#ulog' is the default first tag). This means that his post will populate on https://ulogs.org/created/ulog-unfinishedarts and will also appear as a post, under our primary (umbrella) tag, '#ulog'.

**Now, here is the technical part.....** 

Recall that ulogs.org is an ecosystem that seeks inventive ways of celebrating 'humans'. We being your ultimate "true fans". 

The 'ulog-stories' display column thus, will constitute a UI perk for 'certified uloggers' only. In general, only 'certified uloggers' can be given face on our UI. 

This means that, while every user (certified/non-certified) can use the 'Ulog-Stories editor' to post to the steem blockchain, only such posts from 'certified uloggers' will appear on the 'ulog-stories display column' on ulogs.org

We want to create value for the role "certified" across our UI

First things first, the code algorithm for the 'ulog-stories' segment should be able to ascertain from the onset, whenever users click on the "Add a ulog-story" button, whether the user is a 'certified ulogger' or not. 

If the user is "certified', the post-editor portal that should show up, is this:
![image](https://steemitimages.com/p/7AzetLrHVAgKDqQsV6GrAttY8LLxARkSt24iJyNifMNAiMAfwbq7uXWXdSA1VMEFn2W9hmZtbza68TG3SiEh2y5EiNBqaoVvMapTqK8go3oCJ7eiKZ2gK3f7Fi26wXLbRTogLMAfX2M1fA1Uj9uS9rDyGtTBsfKGx8XJLWBoVgVTgNWD8fRUkgLp7yTVKSFUsKDS9WuyXthxCo9JwVQxXq2jSWjuMhwStj5z7ft8CsW3u7W11VrQL2emVCGKucxYpxP5XT58povs?format=match&mode=fit&width=640)

On the other hand, if user who clicked on the 'add a ulog-story' is not 'certified' (i.e not on the list 'https://steemit.com/@uloggers/followed'), the post-editor portal that should pop up is this:
![image](https://steemitimages.com/p/gPCasciUWmEwHnsXKML7xF4NE4zxEVyvENsPKp9LmDaFuyzZ44PWJhAGJGDJAWAoXjcgVGsfpzUUf6LW6oFwTNgB4UqMZiGhaDnoWnF7oi9EWfPAJGUuL3mgEdWCK43CFwN9Rk6H8N3FTEgJZU?format=match&mode=fit)

**Raw bottom text (for the screenshot):** 
[Please note that while you will be able to successfully post to steem and ofcourse have your post appear on ulogs.org (as a post), your post will not be displayed on our "Ulog-Stories" display-column as this column is reserved for "certified uloggers" only. However, every(any)one can become "certified". We invite you to contact us!]

**Possible algorithm**
When users click on the 'Add a ulog-story' button, check if user is 'certified' or 'not certified' (i.e on the list  'https://steemit.com/@uloggers/followed'). Based on this, pop up corresponding post-editor portal as indicated earlier.

Now, if user is 'certified' and completes a post (ulog-story), his post can appear on the "Ulog-Stories" display-column, else cant!

- This ulog-stories column displays only ulog-stories created by 'certified uloggers'. 
- The 'view' button expands the actual post, like a normal ulogs.org post. 
- The 'view more' button should display more certified ulogger profiles within the same column and their corresponding ulog-stories. (Posts displayed here should populate inorder of "new" or "recent".)

**Comment by Vheissu** [comment]
Hi @surpassinggoogle this is Beggars from Steem. If you wanted to assign this issue to me, that would be great.

**Comment by surpassinggoogle** [comment]
Sorry about delays in responding here. I left a message on discord. I was thinking of a dropdown simply for them to chose a second default tags. for other tags, they will need to type those in themselves. The selector is just for them chose an appropriate second tag, which forms the default second tag, assuming the first tag is #ulog. Being that #ulog is the most popular tag, we still want all posts under any #ulog-subtag not to be lost during curation. So we still want all this posts to appear under #ulog as well as under the #Ulog-subtag e.g #ulog #ulog-diy then a slot where they can type in 3 other tags which can be e.g diy cakes buns etc

I left you a lil message explaining the certified ulogger thing. Yes, that list simply tallies with this list 'https://steemit.com/@uloggers/followed' and update accordingly

**Comment by surpassinggoogle** [comment]
Hi @snackaholic, are you still helping me with completing this task?

**Comment by eastmaels** [comment]
Remaining items:

1. Add the text for non-certified uloggers to the bottom of the quick post editor
2. This ulog-stories column displays only ulog-stories created by 'certified uloggers'.
3. The 'view' button expands the actual post, like a normal ulogs.org post.
4. The 'view more' button should display more certified ulogger profiles within the same column and their corresponding ulog-stories. (Posts displayed here should populate inorder of "new" or "recent".)
