### ISSUE TITLE
Help Us Re-create The default UI-structure For ulog-subtags across ulogs.org and create a 'create a ulog-community' portal. - Plus 130 steem

### ISSUE THREAD

**Issue by surpassinggoogle** [surpassinggoogle/UlogsV2#186]
> A major part of this task have been covered in the completion of previous tasks #202 and #206 

**Complexity:** Pretty easy

> This task may appear hard but it is not. This is because some of the templates that you will need for some aspects of the task, exist in the current code. 
The task is divided into two parts. In one part, we want to create a general template for ulog-subtags all across ulogs.org and in the other part we want to create a portal/form that allows users to create a new ulog-subtag.

Where you find any aspect of the task hard to pull off, simply contact me or leave a comment here and i will write a workaround version of the issue to make the task less-complex. 

### Task

> A ulog-subtag is any hashtag on steem that is prefixed by '#ulog-', e.g #ulog-misunderstood, #ulog-books, #ulog-nurses etc.

Look for all existing 'ulog-subtags' with the exception of the following ulog-subtags, '#ulog-diy, #ulog-howto, #ulog-ned, #ulog-surpassinggoogle, #ulog-quotes, #ulog-snookmadedoit, #ulogifs, #ulog-memes, #ulog-utopian, #ulog-blocktrades, #ulog-bobbylee, #ulog-showerthoughts, #ulog-gratefulvibes, #ulog-kusknee, #ulog-papapepper, #ulography, #ulog-teamsteem, #ulog-dimimp, #ulog-steemjet, #ulog-sweetsssj, #ulog-surfyogi, #ulog-resolutions' and create a default template for these respective URL-spaces that look like this:

![image](https://steemitimages.com/p/32FTXiZsHoAW6noHJDhrg3W8ZKHVFSsLYM859aTDCF8iErGkdFqgaxNEuPGP8sRhUCjN3mdN2xeek4mmroibsxagpB5Ac9Cwqbow3JpWRvmgQBWPga3taaiBZceX6GJxByZxQroz2xUJdM4S?format=match&mode=fit&width=640)

To find a 'similar template' as the one shown above, please visit our homepage on 'https://ulogs.org' and the ulog-community on 'https://ulogs.org/created/ulog-diy' and **you will see the following screens:**

![image](https://cdn.discordapp.com/attachments/403705949761830922/551604121296306189/Screenshot_2019-03-03-11-17-18.png)

![image](https://cdn.discordapp.com/attachments/403705949761830922/551604145321148433/Screenshot_2019-03-03-11-15-50.png)

**While the templates shown above is very similar to what we want, did you notice a slight variation?** 

The new default template we are trying to build in this case is mostly unfilled. It should show a **collapse header component** just underneath the header banner titled; **'convert #ulog-respectivename to a Ulog-Community'**, which when expanded, should have the **default raw-text below:**

[Thank you for beginning the process of creating a Ulog-Community. To further the process, start by contributing ulogs under this very ulog-subtag and inviting others to do the same. You can start now! Simply visit this editor on 'https://ulogs.org/main-editor' to contribute a ulog and make sure to use the ulog-subtag here as one of the tags underneath your post.
To complete the process of creating a Ulog-Community, kindly send an email containing your intention to uloggers@gmail.com
Note: Anyone can choose to complete the process!]

**Also:**

- The 'About Us' Column, should be titled according to the name of the respective ulog-subtag and **will be left blank**, and its 'post now' button would lead to 'https://ulogs.org/main-editor'.
- The 'video embed' column should embed this video (https://youtu.be/kKZ1CixLG2s) as default.
- The 'overseeing uloggers' column will display only the '@ulogs' account by default.

The above template will now also form the default template for every ulog-subtag, whether old or newly-created across ulogs.org, bringing us to the second part of this task:

#### Create a simple portal that gives users the UI-illusion of actually creating a ulog-subtag. 

Normally, on the steem blockchain, users don't have a mechanism to actually 'create a hashtag' e.g via a form or portal. 
They sometimes create a new hashtag unconsciously by creating a comment that contains that hashtag e.g a comment authored on steem containing the tag '#ulog-misunderstood', will instantly create a URL-space on 'https://steemit.com/created/ulog-misunderstood' or on 'https://ulogs.org/created/ulog-misunderstood'

Users can also start a new hashtag by using the new hashtag as one of the hashtags underneath their posts.

We now want users, to have the feeling of 'actually creating new ulog-subtags' via a simple portal, that looks something like this:
![image](https://steemitimages.com/p/7AzetLrHVAgKDqQsV6GrAttY8LLxARkSt24iJyNifMNAiMAfwbq7uXWXdSA1VMEFn2W9hmZtbza68TG3SiEh2y5EiNBqaoVvMapTqvHJBE9aCxhrMvNGmNwjc5Zi7w5WmsH9xPjjEJmmDDCzdamFnEb5S6C7ZRMEpThhwS8zkxxX2855vYPHNJpqkwcHdk2CqDxgarobLY2zSKjPa359i5owaRC4kcXNM3qmoupJSojdwP4LaVwX7PedKZZKWUJUazssugFSsFf1?format=match&mode=fit&width=640)

> The page above can be created on https://ulogs.org/create-community

As simple-looking as the portal appears, it will needs an algorithm, since this portal only creates new hashtags prefixed by 'ulog-' e.g #ulog-misunderstood etc

Based on the overview from earlier, you will notice that this page will need to check the 'syntax' and 'availability' of the 'hashtag name' selected by users. 

By default, each name they select will already be prefixed by "ulog-"

##### Possible algorithm:

- First, prefix 'name' entered by user with '#ulog-'. Check if '#ulog-subtag' chosen complies with the general syntax for steem hashtags (i.e maximum of 19 characters, all small letters and no numerals or special characters), then approve or suggest error.
- Also, check if '#ulog-subtag' chosen by user already exists (i.e scan the steem blockchain for all hashtags prefixed by '#ulog-" for exact match), then approve or suggest error.
- If all parameters are met, proceed to create 'new ulog-subtag' and load up the new page 'https://ulogs.org/created/newulog-subtag'. 

**Special note**: You may not need to build the entire algorithm for this aspect of the task afresh as there is an aspect of the current code that has the framework for checking availability for steem usernames and ensure certain syntax is met.
You can find an implementation of this especially in 'wallets' across ulogs.org e.g when you want to transfer funds, the input box for 'recipients' checks to see if inputted usernames is available and if it follows the correct syntax allowed by the steem blockchain. **See image:**

![image](https://user-images.githubusercontent.com/23729959/57194477-eb3ed400-6f79-11e9-8f89-075630409a85.png)

### Conclusion
Every ulog-subtag newly-created or old, with the exception of our current existing ulog-communities listed in the earlier part of this post, should have a default template that looks like this:
![image](https://steemitimages.com/p/32FTXiZsHoAW6noHJDhrg3W8ZKHVFSsLYM859aTDCF8iErGkdFqgaxNEuPGP8sRhUCjN3mdN2xeek4mmroibsxagpB5Ac9Cwqbow3JpWRvmgQBWPga3taaiBZceX6GJxByZxQroz2xUJdM4S?format=match&mode=fit&width=640)

Users should now have an actual portal/form the allows them to create a ulog-subtag. After users fill and submit this form, a new ulog-subtag should be created, which instantly loads up a page on _'https://ulogs.org/created/newulog-subtag'_

**Comment by nirvanaitsolutions** [comment]
please assign the task to us.
