### ISSUE TITLE
Make All Steemit Posts Render Perfectly On Ulogs.org 

### ISSUE THREAD

**Issue by surpassinggoogle** [surpassinggoogle/UlogsV2#2]
> Look at this two URL(s) below prior to starting this task...

- https://ulogs.org/@ulogs/new-to-ulogs-or-welcoming-new-celebrities-june-25-2018
- https://ulogs.org/@teardrops/teardrops-token-proof-of-tears-the-curation-a-tear-now-has-value-72

**Now compare them to their busy or steemit counterpart-links below: i.e**

- https://busy.org/@ulogs/new-to-ulogs-or-welcoming-new-celebrities-june-25-2018
- https://busy.org/@teardrops/teardrops-token-proof-of-tears-the-curation-a-tear-now-has-value-72

Being that ulogs is a fork of busy, you will expect rendering of steemit posts to be alike and to come out perfect. However, this didn't turn out the case with some steemit posts viewed from ulogs.org e.g see a screenshots below comparing the same post as view from busy and ulogs respectively:

![image](https://user-images.githubusercontent.com/23729959/41992557-63f0f38c-7a7b-11e8-8547-8e02c1e4c52d.png)
**vs**
![image](https://user-images.githubusercontent.com/23729959/41992519-42ef8702-7a7b-11e8-9064-d32041827bba.png)

Some posts render perfectly though when view from ulogs but especially with steemit posts carry more complex formatting (markdown), then display or the render of the post when viewed from ulogs.org comes out skewed.

This isn't suppose to be the case as busy.org renders this same steemit post perfectly and ulogs.org is a fork of busy.

> Please fix, so that all steemit url (posts) render perfectly when viewed from ulogs.org

**Comment by hsynterkr** [comment]
Done!
