### ISSUE TITLE
A Task Request To Complete Issue #183. Additional 50 steem

### ISSUE THREAD

**Issue by surpassinggoogle** [surpassinggoogle/UlogsV2#202]
This task is aimed at completing task #183 previously taken up by other developers but was only partially done. We want you to complete this task.

First, i will explain briefly with images below, what we want to complete in relation to #183.

This is the current look on each ulog-subtag url enlisted below:
![image](https://cdn.discordapp.com/attachments/403705949761830922/550617149513662486/Screenshot_2019-02-28-17-55-34.png)

**Here is a quick summary of what we wanted:

**#183:** Build the UI structure in the screenshot below, onto the enlisted of ulog-subtags (URL) below (prior and post login):

![image](https://cdn.discordapp.com/attachments/403705949761830922/550620195253780483/IMG_20190228_180513.png)

> Note that the bottom-most DM and ulog-games/exchange columns are collapsed by default. 

Start by visiting each of these links below and you will notice what was contributed so far in relation to task #183:

- https://ulogs.org/created/ulog-diy
- https://ulogs.org/created/ulog-howto
- https://ulogs.org/created/ulog-ned
- https://ulogs.org/created/ulog-surpassinggoogle
- https://ulogs.org/created/ulog-quotes
- https://ulogs.org/created/ulog-snookmadedoit
- https://ulogs.org/created/ulogifs
- https://ulogs.org/created/ulog-memes
- https://ulogs.org/created/ulog-utopian
- https://ulogs.org/created/ulog-blocktrades
- https://ulogs.org/created/ulog-bobbylee
- https://ulogs.org/created/ulog-showerthoughts
- https://ulogs.org/created/ulog-gratefulvibes
- https://ulogs.org/created/ulog-kusknee
- https://ulogs.org/created/ulog-papapepper
- https://ulogs.org/created/ulography
- https://ulogs.org/created/ulog-teamsteem
- https://ulogs.org/created/ulog-dimimp
- https://ulogs.org/created/ulog-steemjet
- https://ulogs.org/created/ulog-sweetsssj
- https://ulogs.org/created/ulog-surfyogi
- https://ulogs.org/created/ulog-resolutions
- https://ulogs.org/created/teardrops
- https://ulogs.org/created/untalented

**Comment by surpassinggoogle** [comment]
You will notice that the UI-structure for each of the URLs above look something like this:

![image](https://cdn.discordapp.com/attachments/403705949761830922/549198599016415243/Screenshot_2019-02-24-19-58-55.png)

Now that you have taken a look at what we expect of #183 and what has been done so far, we will now enlist what has not been done, so that we can complete this task.

Recall that this is the screenshot-guide we are following for #183:

![image](https://user-images.githubusercontent.com/23729959/51329629-de70a000-1ab0-11e9-840d-f2f0c541a1cf.png)

**Referencing the screenshot-guide above, here is what is left for #183:**

1. The banner is suppose to be a plain banner possessing a '+' icon, indicating that users can upload a banner. However, when users click on the '+' icon, it should alert them with this message: _This feature is available only to 'certified uloggers'. Kindly get 'certified', then contact uloggers@gmail.com for further inquiries._

2. The left column currently titled 'interesting people' should be called 'overseeing uloggers' and should be completed in relation to the screenshot-guide shown earlier. Also, this column should currently only display the @ulogs account. Then, kindly remove the 'follow' button, leaving only the 'delegate' button. Also this 'overseeing uloggers' column should be placed right under the video-embed column.

3. Kindly improve on the ulog-games/exchanges column by removing the two left/right arrows as they aren't necessary i.e 
![image](https://i.imgur.com/vW5kype.png)

4. Kindly apply this fixes to all the tag-URLs enlisted in the earlier part of this post and replicate this new look to all such tags-urls, **even prior to login.** 

> This completes #183

Additional note:

**Comment by eastmaels** [comment]
Fixed by PR #207, #209 , #210

**Comment by eastmaels** [comment]
Additional fix from #212
