### ISSUE TITLE
Task Request (via Utopian.io): Kindly Help Us Create Basic Pages The Display User-Profile Cards, For Segments Of 'Ulogs.org/grow'. - (Additional Bounty Of 50 Steem)

### ISSUE THREAD

**Issue by surpassinggoogle** [surpassinggoogle/UlogsV2#240]
<html>
<h2>Repository</h2>
<p><a href="https://github.com/surpassinggoogle/UlogsV2">https://github.com/surpassinggoogle/UlogsV2</a> &nbsp;</p>
<blockquote>Ulogs.org blockchain-based social network where everyone can create ULOGS, become "true celebrity" (ULOGGERS), have a community of &nbsp;"true fans" and earn a variety of rewards and the currency called "steem".&nbsp;</blockquote>
<blockquote>It is a fork of busy.org as well. Thus, being familiar with the busy.org helps.&nbsp;&nbsp;</blockquote>
<h1>Details</h1>
<p>Today's task is quite simple. We simply want to enhance our <em>'grow' page,</em> located on https://ulogs.org/grow</p>
<p><strong>Currently it looks like this:</strong></p>
<p><img src="https://steemitimages.com/p/C3TZR1g81UNaPs7vzNXHueW5ZM76DSHWEY7onmfLxcK2iQNDfRY7J9BW9puGmzRwg6H2L15V4yYJK21rrYyjJq3MQdYYsCxMD7FyNmh4zw4s8CAxHv9DS4v?format=match&amp;mode=fit&amp;width=640" width="640" height="1540"/></p>
<p><br></p>
<p>However, all the <em>'click here' buttons </em><em><strong>(seen on the screenshots above)</strong></em><em> </em>aren't functional yet. We now want to make some of these buttons 'functional' by building the pages that they should link to.</p>
<p>We already have a replica of what we want to build on 'https://steemgigs.org/bropro' and <strong>it looks like this:</strong></p>
<p><img src="https://steemitimages.com/640x0/https://steemitimages.com/p/C3TZR1g81UNaPs7vzNXHueW5ZM76DSHWEY7onmfLxcK2iQHBGKTGBy3NJiRVhGthFBzPg1zqwsSDdp8b3Q6DFePQcQdNuh31hKAhsGX5nUQzZNqMue3hfjC?format=match&amp;mode=fit&amp;width=640" width="640" height="356"/></p>
<p><img src="https://steemitimages.com/p/C3TZR1g81UNaPs7vzNXHueW5ZM76DSHWEY7onmfLxcK2iQXZyf9YggsHgh8RfVcMDBTuqbJSCKsj5AzArrzsWG1G36XDtS6wxhZr62yy4K8UFcRRm4YH5xJ?format=match&amp;mode=fit&amp;width=640" width="640" height="358"/></p>
<p><br></p>
<p>Ultimately, the screenshots just above shows a basic hard-coded page featuring a header banner and a set of profile-cards, each possessing a corresponding <em>'buy now' button,</em> that pops up an <em>alert box</em> when clicked upon.</p>
<p><strong>Going back to https://ulogs.org/grow......</strong></p>
<p>We will like to replicate the bropro-page (indicated in the screenshots just above) on ulogs.org, to be linked-to from the <em>'click here' buttons</em> of <strong>these three segments:</strong></p>
<ul>
  <li>15 Mins Session With Your Favorite Mentor</li>
  <li>Apply To Give A 30 Mins Symposium About Your Project On A Popular Steem Community</li>
  <li>How About Extra Clout On Steem Or Outside Steem</li>
</ul>
<blockquote>Kindly maintain the same text, user-profiles, routes and UI-styling etc seen on 'https://steemgigs.org/bropro'</blockquote>
<p><strong>Then, we want one more page......</strong></p>
<p>Going back to ulogs.org/grow, you will notice a row labelled; <strong>"Send Us A Letter, Gift Or Mail".&nbsp;</strong></p>
<p>We want the<em> 'click here' button</em> for this row, to lead to a simple page, that possess a banner (header-text area) and a body of text.</p>
<p>The banner should contain the same words present for this row on <strong>'ulogs.org/grow'</strong>, while the body of the page should contain<em><strong> this text:</strong></em></p>
<p><strong>Send mail, parcel or letter to:</strong> Block 6 Lot 36 Yakal Str Villa Carolina 2, Tunasan, Muntinlupa City, Metro Manila, Philippines (Zip/Postal Code: 1773)</p>
<p><strong>Send email to:</strong> comsilbronze4@gmail.com</p>
<p><strong>Send steem donations to:</strong> @ulogs</p>
<p><strong>Send FIAT donations to:</strong> comsilbronze4@gmail.com</p>
<h1>Component.</h1>
<blockquote>Looking at the existing codes may simplify the task.</blockquote>
<p><strong>If you are a veteran coder and especially, versed with React JS and the busy.org framework,</strong> you can certainly carry out your own build.&nbsp;</p>
<p>If you aren't very versed with coding and you want to attempt the task, we can always discuss possible solutions, logic etc We just may find answers!</p>
<blockquote>Overall, carry out the task according to your preference and&nbsp;expertise, submitting a pull request and thereafter a post, following Utopian's guidelines for Development (contributions). &nbsp;</blockquote>
<h2>Bounty</h2>
<p>This task has <strong>an additional bounty of "50 Steem"</strong>.&nbsp;</p>
<blockquote>Please do well to also publish a <strong>'development post' via utopian-io, after we have merged your PR for possible curation from the utopian.io team</strong></blockquote>
<h2>Deadline</h2>
<p>3 days</p>
<h2>Communication</h2>
<p>You can contact me on:&nbsp; &nbsp; &nbsp; &nbsp;</p>
<ul>
  <li><a href="https://t.me/teardrops_smt"><strong>Telegram </strong></a><strong>(username: </strong><a href="https://steemit.com/@surpassinggoogle"><strong>@surpassinggoogle</strong></a><strong>)</strong></li>
  <li><a href="https://discord.gg/7bUFymy"><strong>Discord</strong></a><strong> (username: surpassinggoogle#1660)</strong></li>
</ul>
<blockquote>You can also indicate interest by leaving a comment underneath this post or on Github.&nbsp;</blockquote>
<blockquote>It is recommended that we are able to&nbsp;discuss, for a better understanding of the task.</blockquote>
<h3><strong>Github</strong></h3>
<p><a href="https://github.com/surpassinggoogle/UlogsV2">https://github.com/surpassinggoogle/UlogsV2</a>&nbsp;</p>
</html>

**Find clearer images at:**
https://ulogs.org/utopian-io/@surpassinggoogle/task-request-via-utopian-io-kindly-help-us-create-basic-pages-the-display-user-profile-cards-for-segments-of-ulogs-org-grow

**Comment by snackaholic** [comment]
See https://github.com/surpassinggoogle/UlogsV2/pull/248 for pr with solved requirements for this issue

**Comment by snackaholic** [comment]
added https://github.com/surpassinggoogle/UlogsV2/pull/252 for the missing css file. sorry for the delay about this, i forgot to check it in with the first commit...

**Comment by snackaholic** [comment]
notification for bropropage: https://github.com/surpassinggoogle/UlogsV2/pull/254

**Comment by snackaholic** [comment]
added 3 pages and changed routes to existing ones: https://github.com/surpassinggoogle/UlogsV2/pull/255
