### ISSUE TITLE
Bug fix for editor action - load correct editor when user clicks edit button of a post

### ISSUE THREAD

**Issue by eastmaels** [surpassinggoogle/UlogsV2#33]
For record purposes, creating this ticket.

![image](https://user-images.githubusercontent.com/29425738/43464229-7e985766-9515-11e8-86d2-f268bd2ec019.png)

Currently, it's hard-coded to `/editor` but this should be dynamically changed based on hashtags used.

**Comment by surpassinggoogle** [comment]
Very special notice. Thank you
