### ISSUE TITLE
Please Help Adjust The Default Display In The Comment Section Across Ulogs.org to Display "Reputation" First.

### ISSUE THREAD

**Issue by surpassinggoogle** [surpassinggoogle/UlogsV2#4]
Kindly adjust the way comments are displayed all across https://ulogs.org

### Current Behavior
As seen on the screenshot below, comments in the comment section, shows "best" by default. Users can chose to display comments by reputation, new, active by clicking on a drop down.
 
![image](https://user-images.githubusercontent.com/23729959/42120842-df74f442-7c54-11e8-910d-3a312ec89d7f.png)

### Expect Behavior
We simple want to make the default display for comments, "reputation", to where users can click on the drop down to chose other options. 
We do this to curb on comments related to phishing links etc we want these comments to always be bottom of the comment threads

**Comment by hsynterkr** [comment]
Done!
