### ISSUE TITLE
Create New Paths And Routes For The Various Segments Present On https://ulogs.org/ulogging

### ISSUE THREAD

**Issue by surpassinggoogle** [surpassinggoogle/UlogsV2#41]
This task is quite simple but perhaps, a bit hard to explain.

It is divided into two parts. The first part is explained in the **screenshot below:**

![ulogs org ulogging](https://user-images.githubusercontent.com/23729959/43685965-4ffa8da0-98f0-11e8-8453-58070cbe07fc.png)

> Simply add an extended drop down to the "more ulogging" area of the pen (editor) icon on ulogs.org top right.

For the second part, we will like 4 collapse components (segments) on https://ulogs.org/ulogging to now be linkable-to, whenever user clicks on:

- More Ulogging
- Ulog-Knowledge-Bank
- Ulog-Fanlove
- SurpassingGoogle

I will try to explain using several screenshots below, covering all scenarios:

### Scenario 1. 
User clicks on the "more ulogging" on the dropdown as seen in the image below:

![ulogs org ulogging2](https://user-images.githubusercontent.com/23729959/43686079-65568044-98f2-11e8-9374-d954b45f5a45.png)

> Note the this is already the case, currently when user clicks on "more ulogging" on ulogs.org. Simply maintain it even after adding the extended dropdown.

### Scenario Two: 
User clicks on ULOG-Knowledge-bank from the extended drop-down of "more ulogging" as seen in the screenshot below:

![ulogs org ulog-knowledge-bank](https://user-images.githubusercontent.com/23729959/43686146-b816cc34-98f3-11e8-968c-e4c1321f91cc.png)

> The user should now be linked to the collapse area for ulog-knowledge-bank, which should be the only area expanded of the page. We can create a sub-URL for this collapse area on https://ulogs.org/ulog-knowledge-bank

### Scenario Three: 
User clicks on Ulog-Fanlove from the extended dropdown of "more ulogging"as seen in the screenshot below:

![ulogs org ulog-fanlove](https://user-images.githubusercontent.com/23729959/43686678-6b5b3584-98fc-11e8-88a9-fd26931abbe2.png)

> The user should now be linked to the collapse area for ulog-fanlove, which should be the only area expanded. We can create a sub-URL for this collapse component on https://ulogs.org/ulog-fanlove

### Scenario 4:
User clicks on Ulog-Fanlove from the extended dropdown of "more ulogging"as seen in the screenshot below:
![ulogs org surpassinggoogle](https://user-images.githubusercontent.com/23729959/43686967-a01fc89e-9900-11e8-9e6e-d189462ca29a.png)
> The user should now be linked to the collapse area for surpassinggoogle, which should be the only area expanded. We can create a sub-URL for this collapse component on https://ulogs.org/surpassinggoogle

### An extra scenario.
Each editor on ulogs.org has an area with a dropdown for " try more ulogging" too. When this is expanded, the dropdown also displays ulog-knowledge-bank, ulog-fanlove and surpassinggoogle

These areas should all also link to the same places described in the prior scenarios above. This is how the "more ulogging" dropdown looks for each editor:
![image](https://user-images.githubusercontent.com/23729959/43687028-58c1fe8a-9901-11e8-9737-60fdfbfcfe46.png)

**Comment by surpassinggoogle** [comment]
thank you bro. I think it is okay that way then since it still all leads to the same page. so we can just no bother much about more ulogging to a page when clicked. just ulog-knowledgebank, fanlove and surpassinggoogle should lead somewhere. I think it is okay that way too since they are all still led to that same page. @eastmaels 

Thank you for taking it up

**Comment by eastmaels** [comment]
Hello @surpassinggoogle already submitted a PR to develop. Still need to submit another PR for extra scenario.
